{
  "hash": "033b267399a67c1754a503f4e529e58c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Estatística Descritiva\"\nformat: html\n---\n\nA **Estatística Descritiva** é a parte da estatística responsável por **coletar, organizar, resumir e apresentar** os dados de forma clara, **sem fazer inferências ou generalizações** sobre uma população maior.\n\n#### ***O que é Estatística Descritiva?***\n\nÉ um **conjunto de técnicas** usadas para **descrever as características principais de um conjunto de dados**, seja por meio de:\n\n-   **Tabelas**\n\n-   **Gráficosu**\n\n-   **Medidas numéricas**\n\n-   Ela ajuda a **entender e visualizar os dados**, mas **não tira conclusões além do que foi observado**.\n\n### **Tipos de Varíaveis**\n\nAs variáveis são características que podem assumir diferentes valores.\n\n***Classificação:***\n\n| Tipo de Variável | Subtipo  | Exemplos                          |\n|------------------|----------|-----------------------------------|\n| Qualitativa      | Nominal  | Cor dos olhos, sexo, estado       |\n|                  | Ordinal  | Grau de escolaridade, nota(A,B,C) |\n| Quantitativa     | Discreta | Número de filhos, chamadas        |\n|                  | Contínua | Altura, peso, tempo               |\n\n### **Análise Exploratória de variáveis Quantitativas e Qualitativas**\n\nA **análise exploratória de dados (AED)** tem como objetivo **entender as características principais dos dados** antes de aplicar modelos estatísticos. Ela varia conforme o **tipo de variável**: **quantitativa** ou **qualitativa**.\n\n#### **. Variáveis Quantitativas**\n\nSão aquelas que representam **valores numéricos** e podem ser medidas ou calculadas (ex: altura, peso, salário, idade).\n\n***a. Medidas de Tendência Central***\n\nIndicadores do “centro” dos dados:\n\n-   **Média**: soma dos valores dividida pelo total.\n\n-   **Mediana**: valor central após ordenar os dados.\n\n-   **Moda**: valor mais frequente.\n\n***b. Medidas de Dispersão***\n\nMostram o grau de **variação ou espalhamento** dos dados:\n\n-   **Amplitude**: diferença entre maior e menor valor.\n\n-   **Desvio padrão**: média da distância dos dados à média.\n\n-   **Variância**: desvio padrão ao quadrado.\n\n***c. Representações Gráficas***\n\n-   **Histograma**: mostra a distribuição dos valores em intervalos.\n\n-   **Boxplot (diagrama de caixa)**: destaca a mediana, quartis e outliers.\n\n-   **Gráfico de densidade**: versão suavizada do histograma.\n\n#### **. Variáveis Qualitativas**\n\n***Frequência Absoluta***\n\n-   É o **número de vezes** que uma categoria aparece.\n\n-   Exemplo: 20 pessoas preferem o produto A.\n\n***Frequência Relativa***\n\n-   É a **proporção** ou **percentual** que uma categoria representa dentro do total.\n\n-   Cálculo:\n\n    $\\text{Frequência relativa} = \\frac{\\text{Frequência absoluta}}{\\text{Total de observações}} \\times 100\\%$\n\n    #### **Gráficos Usados**\n\n    **Gráfico de Barras**\n\n    -   Cada barra representa uma categoria.\n\n    -   A altura da barra mostra a frequência (absoluta ou relativa).\n\n    -   É o gráfico mais comum para variáveis qualitativas.\n\n    **Gráfico de Setores (Pizza)**\n\n    -   Cada “fatia” representa uma categoria proporcionalmente à sua frequência relativa.\n\n    -   Útil para mostrar **percentuais** de participação.\n\n    **Gráfico de Pareto**\n\n    -   Combina **gráfico de barras** com **linha acumulada**.\n\n    -   As categorias são organizadas da **mais frequente para a menos frequente**.\n\n    -   Ajuda a identificar o **“pouco que causa muito”** (Princípio de Pareto – 80/20).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exemplo com dados fictícios\nsexo <- c(\"F\", \"M\", \"F\", \"F\", \"M\")\nidade <- c(23, 25, 22, 26, 28)\n\n# Tabela de frequência\ntable(sexo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsexo\nF M \n3 2 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Média, mediana e moda\nmean(idade)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.8\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(idade)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25\n```\n\n\n:::\n\n```{.r .cell-code}\nas.numeric(names(sort(table(idade), decreasing=TRUE))[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22\n```\n\n\n:::\n\n```{.r .cell-code}\n# Boxplot\nboxplot(idade, main=\"Boxplot Idade\")\n```\n\n::: {.cell-output-display}\n![](descritiva_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n### **Análise bidimensional**\n\nA **análise bidimensional** (ou análise bivariada) tem como objetivo **investigar a relação entre duas variáveis**. Dependendo do tipo de variável (qualitativa ou quantitativa), utilizam-se métodos diferentes para essa análise.\n\n#### **Tipos de análise:**\n\n***• Tabela de contingência***:\n\n-   Usada quando **ambas as variáveis são qualitativas** (ou categóricas).\n\n-   Mostra a **frequência conjunta** de ocorrência das categorias das duas variáveis.\n\n-   Permite analisar se existe **dependência** ou **associação** entre elas.\n\n-   **Exemplo:** Uma tabela cruzando **gênero** (masculino/feminino) e **preferência de produto** (A/B/C).\n\n***• Diagrama de dispersão***:\n\n-   Utilizado quando **ambas as variáveis são quantitativas**.\n\n-   Cada ponto no gráfico representa um par de valores (x, y).\n\n-   Permite **visualizar a forma da relação** entre as variáveis: linear, exponencial, nenhuma, etc.\n\n-   **Exemplo:** Analisar a relação entre **tempo de estudo** e **nota em uma prova**.\n\n***• Coeficiente de correlação (r):*** força e direção da relação linear.\n\n-   Mede a **força** e a **direção** da relação **linear** entre duas variáveis quantitativas.\n\n-   Varia entre -1 e +1:\n\n    | Valor de r | Interpretação |\n    |------------------------------------|------------------------------------|\n    | $r = +1$ | Correlação perfeita positiva |\n    | $r= -1$ | Correlação perfeita negativa |\n    | $r= 0$ | Sem correlação linear |\n    | $0.7 <= |r| < 1$ | A correlação é **forte**, seja ela positiva (r \\> 0) ou negativa (r \\< 0) |\n    | $0.3 <=|r| < 1$ | A correlação é **modera**, seja ela positiva (r \\> 0) ou negativa (r \\< 0) |\n    | $0 <|r|<0.3$ | A correlação é **fraca**, seja ela positiva (r \\> 0) ou negativa (r \\< 0) |\n\n-   **Importante**: correlação **não implica causalidade**.\n\n-   **Exemplo:** Se r = 0.85, há **forte correlação positiva**: à medida que uma variável aumenta, a outra tende a aumentar também.\n\n***• Regressão linear simples:*** modela relação entre duas variáveis numéricas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(10, 20, 30, 40, 50)\ny <- c(15, 25, 29, 41, 49)\n\n# Correlação\ncor(x, y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9921567\n```\n\n\n:::\n\n```{.r .cell-code}\n# Regressão\nmodelo <- lm(y ~ x)\nsummary(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = y ~ x)\n\nResiduals:\n         1          2          3          4          5 \n 8.547e-16  1.600e+00 -2.800e+00  8.000e-01  4.000e-01 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   6.6000     2.0265   3.257 0.047244 *  \nx             0.8400     0.0611  13.748 0.000833 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.932 on 3 degrees of freedom\nMultiple R-squared:  0.9844,\tAdjusted R-squared:  0.9792 \nF-statistic:   189 on 1 and 3 DF,  p-value: 0.0008329\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot\nplot(x, y, main=\"Dispersão com Regressão\")\nabline(modelo, col=\"blue\")\n```\n\n::: {.cell-output-display}\n![](descritiva_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nEsse é o **resultado de uma regressão linear simples** obtida em R com o modelo lm(y \\~ x). Vamos **interpretar detalhadamente** cada parte do output:\n\n### **Resumo do Modelo**\n\ny = 6,6 + 0,84x\n\n#### **1.Coeficientes (Estimate)**\n\n| Termo | Valor | Interpretação |\n|------------------------|------------------------|------------------------|\n| (Intercept) | 6.6000 | Quando x = 0, a previsão de y é 6.6 |\n| x | 0.8400 | A cada aumento de 1 unidade em x, y aumenta em média 0.84 unidades |\n\n#### **2. Significância dos Coeficientes**\n\n| Termo       | Pr(\\>\\|t\\|) | Interpretação                     |\n|-------------|-------------|-----------------------------------|\n| (Intercept) | 0.047244    | Significativo ao nível de 5% (*)* |\n| x           | 0.000833    | *Muito significativo (*\\*\\*)      |\n\nA variável x tem um **forte efeito estatístico sobre** y, com **baixo p-valor** (menor que 0.001)\n\n#### **Como interpretar esses valores:**\n\n-   O **p-valor** mede a **probabilidade de obter um coeficiente igual ou mais extremo**, assumindo que ele é **nulo** (sem efeito).\n\n-   Se o p-valor for **menor que 0,05**, consideramos o coeficiente **estatisticamente significativo** (ao nível de 5%).\n\n    -   **Códigos de significância usados em R:**\n\n        | **Código** | Nível de significância              |\n        |------------|-------------------------------------|\n        | \\*\\*\\*     | p\\<0.001                            |\n        | \\*\\*       | p\\<0.01                             |\n        | \\*         | p\\<0.05                             |\n        | .          | p\\<0.1(marginalmente significativo) |\n        | (vazio)    | p\\>= 0.1(não significativo)         |\n\n#### **3. Erro padrão residual**\n\n$\\text{Residual standard error} = 1.932$\n\n→ Em média, o modelo erra em cerca de **1,93 unidades de** y.\n\n#### \n\n**4. R² (R-squared)**\n\n$R^2 = 0.9844$\n\n→ O modelo explica **98,44% da variação de** y com base em x.\n\nÉ um modelo **extremamente ajustado aos dados**.\n\n#### **5. Estatística F**\n\n$F = 189,\\quad p\\text{-value} = 0.0008329$\n\n→ Indica que o modelo é **estatisticamente significativo** como um todo.\n\nHá evidências fortes de que **pelo menos um coeficiente (neste caso,** x**) é diferente de zero**.\n\n#### **Conclusão:**\n\n-   O modelo é **forte e ajustado**.\n\n-   A variável x é altamente significativa.\n\n-   R² muito alto indica que quase toda a variação de y é explicada por x.\n\n-   O modelo pode ser confiável para **previsão e interpretação**, com base nessa amostra.\n\n### **EXEMPLOS COMPUTACIONAIS EM R E PYTHON**\n\n#### ***Dataset real (opcional para prática):***\n\n• iris, mtcars, penguins (R)\n\n• seaborn.load_dataset('iris'), titanic (Python)\n\n#### ***Recursos online:***\n\n• Kaggle Datasets\n\n• UCI Machine Learning Repository\n\n### **Referências Gerais Complementares**\n\n```         \n1.  Triola, M. F. Introdução à Estatística.\n2.  Bussab, W. O., Morettin, P. A. Estatística Básica.\n3.  Moore, D. S. et al. A Prática da Estatística.\n4.  Tukey, J. W. Exploratory Data Analysis.\n5.  McKinney, W. Python for Data Analysis, O’Reilly, 2022.\n6.  Wickham, H., Grolemund, G. R for Data Science, O’Reilly, 2017 (acesso livre: r4ds.had.co.nz).\n```\n",
    "supporting": [
      "descritiva_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}